config/routes.rb
Rails.application.routes.draw do
  
  resources :user_stocks, only: [:create, :destroy]
  resources :freindships, only: [:create, :destroy]
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to:'users#my_freinds'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#home"

  get 'stocks_search', to:'stocks#search'
  get 'freinds_search', to:'users#search'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/freindship.rb
class Freindship < ApplicationRecord
  belongs_to :user
  belongs_to :freind, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users ,  through: :user_stocks
  #to define class methods use self.method name

  validates :name,:ticker, presence: true
  def self.look_up(symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:normal_token] ,
      secret_token: Rails.application.credentials.iex_client[:secret_token] ,
      endpoint: 'https://sandbox.iexapis.com/v1')

    #we don't need to write its implied.
    begin
      new(ticker: symbol, name: client.company(symbol).company_name,last_price: client.price(symbol))
    rescue => exception
      nil
    end
  end

  def self.check_db(symbol)
    where(ticker: symbol ).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :user_stocks
  has_many :stocks , through: :user_stocks
  
  has_many :freindships
  has_many :freinds, through: :freindships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def stock_already_tracked?(ticker_symbol)

    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id:stock.id).exists?

  end
    def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(symbol)
    under_stock_limit? and !stock_already_tracked?(symbol)
  end

  def fullname
    return first_name+" "+last_name if first_name or last_name
    return "Anonymous"
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id } 
  end

  def not_friends_with?(id)
    !self.freinds.where(id: id).exists?
  end
  def self.search(param)
    param.strip! #remove spaces
    return_string = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless return_string
    return return_string

  end

  def self.first_name_matches(param)
    self.matches('first_name',param)
  end
  
  def self.last_name_matches(param)
    self.matches('last_name',param)
  end
  
  def self.email_matches(param)
    self.matches('email',param)
  end
  
  def self.matches(field_name,param)
    where("#{field_name} like ?","%#{param}%")
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
  end

end

app/controllers/freindships_controller.rb
class FreindshipsController < ApplicationController
  def create
    friend = User.find(params[:freind])
    current_user.freindships.build(freind_id: friend.id)
    if current_user.save
      flash[:notice] = "Following Friends"
    else
      flash[:alert] = "There was something wrong with the request"
    end
    redirect_to my_friends_path
  end

  def destroy
    freindship = current_user.freindships.where(freind_id: params[:id]).first
    freindship.destroy
    flash[:notice] = "Stopped Following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.look_up(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial:'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert]= "Please Enter Any Symbol"
          format.js { render partial:'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert]= "Please Enter a Valid Symbol"
        format.js { render partial:'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.look_up(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user , stock: stock)
    flash[:notice] = "Stocks #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(stock_id: stock.id, user_id: current_user.id).first
    @user_stock.destroy
    flash[:notice] = "#{stock.ticker} is delete successfully"
    redirect_to my_portfolio_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user 
    @tracked_stocks = current_user.stocks
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  
  def my_freinds
    @my_freinds_list = current_user.freinds
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial:'friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert]= "Couldn't find user"
          format.js { render partial:'friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert]= "Please Enter a friend name or email to search"
        format.js { render partial:'friend_result' }
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/freindships_helper.rb
module FreindshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
      <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "My PortFolio", my_portfolio_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <div class="btn btn-info mr-2">
            <%= fa_icon 'user' %> <%=  current_user.fullname%>
          </div>
          <li class="nav-item active">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          </li>
        </ul>
        <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to "Sign up", new_user_registration_path , class: "btn btn-info" %>
          </li>
        </ul>
        <% end %>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= render 'layouts/message'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row mt-4">
  <div class="col-9 ">
    <h3>Stocks Table</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Last Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% for stock in @tracked_stocks%>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <% if stock.last_price==nil %>
            <td>Not Updated</td>
          <% else %>
            <td><%= stock.last_price %></td>
          <% end %>
          <td><% if current_user == @user %> 
                <%= link_to 'Remove' ,user_stock_path(stock),method: :delete, data: {confirm: 'Are your Sure'}, class: 'btn btn-sm btn-warning'%>
              <% else %>
                <% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to "Add To Portfolio" , user_stocks_path(user: current_user, ticker:stock.ticker), method: :post, class: "btn btn-success"%>
                <% else %>
                  <span class="badge badge-secondary">
                    You are already tracking
                    <% if !current_user.under_stock_limit?%>
                      10 stocks
                    <% else %>
                      this stock
                    <% end %>
                  </span>
                <% end %>
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="row">
  <div class="col-9">
  <%= render 'layouts/message'%>
  </div>
</div>

<% if @friends %>
  <% @friends.each do | item | %>
  <div class="card card-header results-block">
      <strong>Name: </strong> <%= item.fullname %>
      <strong>Email: </strong> <%= item.email %>
      <%= link_to "View Profile",user_path(item),class: "btn btn-sm btn-success" %> 
      <% if current_user.not_friends_with?(item.id) %>
        <%= link_to "Follow Friend?" , freindships_path(freind: item), method: :post, class: "btn btn-sm btn-success"%>
      <% else %>
        <span class="badge badge-secondary">
          You are already friends
        </span>
      <% end %>
  </div>
  <br><br>
  <% end %>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#result').innerHTML = '<%=escape_javascript(render 'friend_result.html')%>'

app/views/users/_list.html.erb
<div class="row mt-4">
  <div class="col-9 ">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% for item in @my_freinds_list%>
        <tr>
          <th scope="row"><%= item.email %></th>
          <td><%= item.first_name %></td>
          <td><%= item.last_name %></td>
          <td>
              <%= link_to 'Stop Following' ,freindship_path(item) ,method: :delete, data: {confirm: 'Are your Sure'}, class: 'btn btn-sm btn-warning'%>
              <%= link_to "View Profile",user_path(item),class: "btn btn-sm btn-success" %> 
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<div class="row">
  <div class="col-9">
  <%= render 'layouts/message'%>
  </div>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker%>
    <strong>Company Name: </strong> <%= @stock.name%>
    <strong>Price: </strong> <%= @stock.last_price%> 
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to "Add To Portfolio" , user_stocks_path(user: current_user, ticker:@stock.ticker), method: :post, class: "btn btn-success"%>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit?%>
          10 stocks
        <% else %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#result').innerHTML = '<%=escape_javascript(render 'users/result.html')%>'

app/views/users/my_freinds.html.erb
<h1>Friends</h1>

<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag freinds_search_path,remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Search Friends", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

<div id="result">
  
</div>


<% if not @my_freinds_list.empty? %>
  <%= render 'list'%>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag stocks_search_path,remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

<div id="result">
  
</div>

<% if not @tracked_stocks.empty? %>
<%= render 'stocks/list'%>

<% end %>

app/views/users/show.html.erb
<h2>User's Details</h2>

<dl class="row">
  <dt class="col-sm-3">Full Name</dt>
  <dd class="col-sm-9"><%=@user.fullname %></dd>

  <dt class="col-sm-3">Email</dt>
  <dd class="col-sm-9">
    <p><%= @user.email %></p>
  </dd>

  <dt class="col-sm-3">No.of Friends</dt>
  <dd class="col-sm-9"><%= @user.freinds.count %></dd>

  <dt class="col-sm-3">No. of Stocks Following </dt>
  <dd class="col-sm-9"><%= @user.stocks.count %></dd>

  <dt class="col-sm-3">
  <% if current_user.not_friends_with?(@user.id) %>
      <%= link_to "Follow Friend?" , freindships_path(freind: @user), method: :post, class: "btn btn-lg btn-success"%>
  <% else %>
    <span class="btn btn-lg btn-info">
      You are already friends
    </span>
  <% end %>
  </dt>
</dl>

<h2><%= @user.fullname %>'s Stocks</h2>
<% if not @tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% end %>

app/views/welcome/home.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
</head>
<body>
  <h1></h1>
  <div class="container" id="home-container">
    <div class="jumbotron">
      <h1 class="display-4">Finance Tracker</h1>
      <p class="lead">Welcome to Finance - Tracker</p>
      <hr class="my-4">
      <p> You can follow your friends, add stocks, create your profiles .</p>
    </div>
  </div>
</body>
</html>